accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.conf.urls.static import static
from .views import *

app_name= 'accounts'
urlpatterns = [
    url(r'^$', user_login, name='user-login'),
    url(r'^logout-user$', logout_user, name='logout-user'),
    url(r'^cadastrar-usuario$', cadastrar_usuario, name='cadastrar-usuario'),
    url(r'^sucesso$', sucesso, name='sucesso'),
]

projectoLogin/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^', include(('accounts.urls', 'accounts'), namespace="'accounts")),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Primeiro nome'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Último nome'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'password': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Palavra-passe'}),
            'password2': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Confirme a sua palavra-passe'}),
        }

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import (authenticate, login, logout, update_session_auth_hash)
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .forms import *

# Create your views here.

def cadastrar_usuario(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('first_name')
            messages.success(request,'Olá ' + username + '! A sua conta criada com sucesso')
            return HttpResponseRedirect(reverse('accounts:user-login'))
    context = {'form':form}
    return render(request, 'accounts/signupPage.html',context)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        usuario = User.objects.filter(username = str(username))
        password = request.POST.get('password')
        if usuario.exists():
            user = authenticate(request, username = username , password = password)
            if user is not None:
                login(request,user)
                messages.success(request, 'Login feito')
                return HttpResponseRedirect(reverse('accounts:sucesso'))
            else:
                messages.warning(request, 'Palavra-passe incorreta')
                return render(request, 'accounts/index.html')
        else:
            messages.warning(request, 'Usuário não existe ou campos vazios')
            return render(request, 'accounts/index.html')
    context = {}
    return render(request, 'accounts/index.html',context)

def sucesso(request):
    return render(request, 'accounts/sucesso.html')

def logout_user(request):
    logout(request)
    return user_login(request)

templates/accounts/index.html
{% extends 'base_login.html' %}
{% block content %}


    
    <section>
        <div class="container">
            <div class="row espaco-m-top-2">
                <div class="col s12 m12 l12 center-align">
                    <h4>Faça o seu login</h4>
                </div>

                {% if messages %}
                    {% for message in messages %}
                        <ul class="collection">
                            <li class="collection-item grey lighten-4 lighten-4"><strong>{{message}}</strong> </li>
                        </ul>
                    {% endfor %}
                {% endif %}

                <div class="col s12 m6 l6 offset-l3 offset-m3">
                        <form  method="POST">
                            {% csrf_token %}
                                <div class="row">
                                    <div class="col s12">
                                        <input type="text" id="id_username" name="username" class="estilo-input browser-default">
                                    <label for="">Username</label>
                                    </div>
                                </div>
                                
                                    <div class="row">
                                        <div class="col s12">
                                            <input type="password" id="id_password" name="password" class="estilo-input browser-default">
                                            <label for="">Password</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col s12">
                                            <button type="submit" class="btn col s12 orange">Entrar</button>
                                        </div>
                                        <div class="col s12 center-align">
                                            <p>Ainda não possui uma conta? <a href="{% url 'accounts:cadastrar-usuario' %}">Crie uma</a></p>
                                        </div>
                                </div>
                                </div>
                        </form>
                </div>
            </div>
        </div>
        
        <div class="container center">
            <hr>

            <p>Created by: Anilésio Xavier</p>
            <a href="">linkedin</a>
            <a href="">github</a>
        </div>
    </section>



{% endblock %}

templates/accounts/signupPage.html
{% extends 'base_login.html' %}
{% block content %}


    
    <section>
        <div class="container">
            <div class="row espaco-m-top-2">
                <div class="col s12 m12 l12 center-align">
                    <h4>Crie uma conta</h4>
                </div>

                {% if messages %}
                {% for message in messages %}
                    <ul class="collection">
                        <li class="collection-item grey lighten-4 lighten-4"><strong>{{message}}</strong> </li>
                    </ul>
                {% endfor %}
            {% endif %}

                <div class="col s12 m8 l8 offset-l2 offset-m2">
                        <form  method="POST">
                            {% csrf_token %}
                                <div class="row">
                                    <div class="col s12 m6 l6">
                                        <input type="text" id="id_first_name" name="first_name" class="estilo-input browser-default">
                                    <label for="">Primeiro nome</label>
                                    </div>

                                    <div class="col s12 m6 l6">
                                        <input type="text" id="id_last_name" name="last_name" class="estilo-input browser-default">
                                        <label for="">Último nome</label>
                                    </div>
                                </div>
                                
                                    <div class="row">
                                        <div class="col s12 m6 l6">
                                            <input type="email" id="id_email" name="email" class="estilo-input browser-default">
                                            <label for="">Email</label>
                                        </div>
                                        <div class="col s12 m6 l6">
                                            <input type="text" id="id_username" name="username" class="estilo-input browser-default">
                                            <label for="">Username</label>
                                        </div>
                                    </div>


                                    <div class="row">
                                        <div class="col s12 m6 l6">
                                            <input type="password" id="id_password1" name="password1" class="estilo-input browser-default">
                                            <label for="">Palavra-passe</label>
                                        </div>
                                        <div class="col s12 m6 l6">
                                            <input type="password" id="id_password2" name="password2" class="estilo-input browser-default">
                                            <label for="">Repita a Palavra-passe</label>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col s12">
                                            <button type="submit" class="btn col s12 green">Registar</button>
                                        </div>
                                        <div class="col s12 center-align">
                                            <p>Já possui uma conta? <a href="{% url 'accounts:user-login' %} ">Entre</a></p>
                                        </div>
                                </div>
                                </div>
                        </form>
                </div>
            </div>
        </div>
        
        <div class="container center">
            <hr>

            <p>Created by: Anilésio Xavier</p>
            <a href="">linkedin</a>
            <a href="">github</a>
        </div>
    </section>

{% endblock %}

templates/accounts/sucesso.html
{% extends 'base_login.html' %}
{% block content %}


<section>
    <div class="container">
        <div class="row espaco-m-top-2">
            <div class="col s12 m10 l10 offset-l1 offset-m1 center-align">

                {% if messages %}
                    {% for message in messages %}
                        <ul class="collection">
                            <li class="collection-item grey lighten-4 lighten-4"><strong>{{message}}</strong> </li>
                        </ul>
                    {% endfor %}
                {% endif %}


                <h1>Parabéns {{request.user.first_name}} </h1>
                <h1> </h1>
                <h5><strong>Você concluiu o seu cadastro</strong></h5>
                <div class="espaco-m-top-2">
                    <a href="{% url 'accounts:logout-user' %}" class="btn red pulse">Terminar sessão</a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/base_login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-pt">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %} ">
    <link rel="stylesheet" href="{% static 'css/style.css' %} ">
    <title>Login page</title>
</head>
<body>

    <div style="padding: 10px; font-size: 2em; background-color:#aded64; width: 500px; font-weight: bold;">
        HTML + CSS + Django(Python)
    </div>

    {% block content %}

    {% endblock %}

    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/materialize.min.js' %}"></script>

</body>
</html>